epoch: 100
batch_size: 8
num_worker: 8
classes: 11
lr: 0.0001
decoder: UnetPlusPlus # Unet, UnetPlusPlus, DeepLabV3, DeepLabV3Plus
encoder: timm-efficientnet-b3 # Segmentation Model 보는게 더 빠름
encoder_weights: imagenet # imagenet / advprop / noisy-student
criterion: CE # dice / CE / focal / softCE
